---
title: "RAPTOR analysis"
author: "Susannah Fleming"
date: "2023-11-23"
output: word_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r sourcing}
library(knitr)
library(ggplot2)
source("DTAinterimAnalysis.R")
```

2 devices.  
Assume planned interim analysis after 50, 100 and 150 positive results, although exact numbers differ because multiple data come in on one day.  
Ignore end of study data (>150 positives)



```{r setupdata}

# load RAPTOR data
raptor <- read.csv("Z:\\Stats_Group_Projects\\Interim_analysis_DTA\\RAPTORdata.csv")

# remove rows where there are more than 150 positives
raptor <- raptor[raptor$n.positives<=150, ]

# recode column names for compatibility
raptorcols <- colnames(raptor)
raptorcols[raptorcols=="n.positives"] <- "RefT"
raptorcols[raptorcols=="n.total"] <- "N"
colnames(raptor) <- raptorcols


```

Planned sample size is npos=150

Planned prevalence is 0.3 (30%)

Desirable p0 is Se=0.97 and Sp=0.99
Acceptable p0 is Se=0.8 and Sp=0.95

```{r run_dta}

Nposplanned = 150
prevplanned = 0.3
p0 <- data.frame(type=c("Desirable", "Acceptable"),
                 Se = c(0.97, 0.8), 
                 Sp = c(0.99, 0.95))

# run each analysis separately to properly show interim performance
dtaresults <- data.frame()

# run each device separately
for(p in 1:2){
  thisp0 <- p0[p, ]
  for(t in 1:nrow(raptor)){
    thisdata <- raptor[t, ]
    thistest <- DTAcumulativeInterimAnalysis(thisdata, pSe=thisp0$Se, pSp=thisp0$Sp, 
                                          positiveN=Nposplanned, prevalence = prevplanned,
                                          simpleOutput=F)
    # collect useful output
    opdta <- data.frame(device=thisdata$Device,
                        Npos = thisdata$RefT,
                        p0type = thisp0$type,
                        Se = thisdata$Sens,
                        Sp = thisdata$Spec, 
                        Sefut=1-(thistest$Sensitivity$details$Crit_rg/thistest$Sensitivity$details$Cumulative_N),
                        Seeff=1-(thistest$Sensitivity$details$Crit_ag/thistest$Sensitivity$details$Cumulative_N),
                        Spfut=1-(thistest$Specificity$details$Crit_rg/thistest$Specificity$details$Cumulative_N), 
                        Speff=1-(thistest$Specificity$details$Crit_ag/thistest$Specificity$details$Cumulative_N),
                        Sedecision=thistest$Sensitivity$details$Decision, 
                        Spdecision=thistest$Specificity$details$Decision)
    dtaresults <- rbind(dtaresults, opdta)
  }
}

# make it 0-100 not 0-1
dtaresults[, 4:9] <- dtaresults[, 4:9] *100


```

Results of analysis:

`r kable(dtaresults, digits=1)`

```{r graphs}

# add factor variable 
dtaresults$Positives <- factor(dtaresults$Npos)

raptorfig <- ggplot(data=dtaresults, aes(x=Sp, y=Se, label=Positives, color=Positives, fill=Positives, linetype=Positives)) +
  geom_rect(aes(xmin=Spfut, xmax=100, ymin=Sefut, ymax=100), alpha=0.1) +
  geom_text() +
  coord_cartesian(xlim=c(80,100), ylim=c(50,100), expand=FALSE) +
  labs(x="Specificity (%)", y="Sensitivity (%)") +
  facet_grid(device ~ p0type) +
  theme_bw()
print(raptorfig)




```


```{r savegraphs, eval=FALSE}

ggsave("raptor.png",width=8,height=8)


```